### ISSUE TITLE
Fusion 360 freezes after starting *solved*

### ISSUE THREAD

**Issue by enstain-tm** [cryinkfly/Autodesk-Fusion-360-for-Linux#135]
Hello, 
I have recently moved to Linux, and having Fusion 360 forking on it was the last cord I needed to cut from Windows. I am running Zorin OS 16 (based on Ubuntu 20.04.3 LTS). I have installed with the script, it ran fine the first time (although the desktop shortcut wouldn't work, but the one that opens  the little bash launcher window works). But now, it starts up and is very very slow. Eventually I get offered to force quit. Is there anything I can try or look in to?
I have a XFX Radeon RX 580 8GB GTX Core video card, 16 gb of ram and some AMD processor (from the previous generation with the AM3+ slot).
Thank you for the work you are doing and any help you can provide. :)

**Comment by cryinkfly** [comment]
The Autodesk Fusion 360 seems a bit slower because the internet connection is not using the full potential under Wine at the moment! :-1: 

The Autodesk Fusion 360 should be closed, for example under Gnome, because the start takes a long time.
You just have to ignore that!

This is due to the fact that packages are downloaded over and over again every time it's started, because it's a cloud program.

**Comment by enstain-tm** [comment]
No, apparently the issue was that the install script makes the launcher.sh file in the wrong format. I replaced it with the contents I found in one of the closed issues, and everything runs well.
