### ISSUE TITLE
How do I update fusion?

### ISSUE THREAD

**Issue by wprojects** [cryinkfly/Autodesk-Fusion-360-for-Linux#164]
Fusion gives me a notification when I start it up that there is an update and to contact my system administrator. How can I update it, I am not able to open certain files that I am working on from my mac because I my version on linux is outdated

**Comment by cryinkfly** [comment]
You can use my Setup Wizard again, because you get another window where you can update your Fusion 360. :+1:

**Comment by wprojects** [comment]
It is just asking me to install it, I am not getting another window

**Comment by wprojects** [comment]
![image](https://user-images.githubusercontent.com/57518634/148663220-753ca5a6-b264-4274-a782-91921073c4b3.png) What do I do here after I install?

**Comment by cryinkfly** [comment]
When you update your Autodesk Fusion 360 then you must see in your picture the path and in the next step you must select the folder with the filemanager.

**Comment by wprojects** [comment]
Is the correct folder this one? The root of the folder I downloaded? The first option was something with root and fusion 360, this folder I sent the pic of is in my downloads
![image](https://user-images.githubusercontent.com/57518634/148707002-af87c442-1442-47cf-9234-53e19ca3a1f1.png)

**Comment by cryinkfly** [comment]
No. What I mean is, if you selected the standard installation when you installed Autodesk Fusion 360, then the program is installed here:

> /$HOME/.wineprefixes/fusion360

And this path should be with your picture here:

![update-exist-f360](https://user-images.githubusercontent.com/57518634/148663220-753ca5a6-b264-4274-a782-91921073c4b3.png)

... be visible!

In any case, it is important that you should check whether the fusion360 folder exists, regardless of what is displayed in the picture. Because it may be that something has changed with an update of my setup wizard.

You can of course also do the following, provided Autodesk Fusion 360 has been installed on your system in /$HOME/.wineprefixes/fusion360:

1.) Download the installer or or change to the folder where the EXE file is already located.

    wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe -O Fusion360installer.exe

2.) Install Autodesk Fusion 360 without any extensions.

       WINEPREFIX=$HOME/.wineprefixes/fusion360 wine Fusion360installer.exe -p deploy -g -f log.txt --quiet

**Comment by wprojects** [comment]
So I check off I have changed the path of the folder and hit ok with nothing in that box? I did that last time and it didn't work. Or am I supposed to put something in the box, if I am what am I supposed to put in there

**Comment by wprojects** [comment]
Still confused on this
