### ISSUE TITLE
Freeze after Splashscreen, Fusion completely unreactive

### ISSUE THREAD

**Issue by thomas-repo** [cryinkfly/Autodesk-Fusion-360-for-Linux#213]
So I I've got a problem with trying to get Fusion360 running on my Manjaro System.

**Describe the bug**
After succesfully (there are a lot of fixme and errors within the console?) installing Fusion360 via the installer script. When I try to launch it the first time after a clean install I get prompted to log in with Username/Password. So far so good, but then after the Fusion360 Logo Splashscreen hast went away and it seems than Fusion had been loaded the following happens. 

I already tried to do what in issue #79 was meantioned, sadly it did not change anything.

**To Reproduce**
1. Launching Fusion via the .desktop Shortcut file provided by the Installer
2. The Login comes, I can log in
3. The Splashscreen comes and goes away as expected

4. the only window I can interact with is the Info Box "About your Fusion Documents" then I click on "Got it" 
![2022-04-07_08-25-54_1920x2160](https://user-images.githubusercontent.com/39732028/162134135-25c9cb12-c89a-44d3-b459-b1e767883a76.png)

5. the Window then goes away and I'm promted with the expected looks of Fusion
![2022-04-07_08-27-02_1920x2160](https://user-images.githubusercontent.com/39732028/162134294-ede2e98f-abf0-4905-b414-d626ac265f04.png)

***here starts the problem***
6. with and without moving the main Window, all Applets got stuck, nothing is reactive nor clickable, neither are keyboard shortcuts working, it seems to be completely frozen
![2022-04-07_08-09-46_1920x2160](https://user-images.githubusercontent.com/39732028/162132918-1dcbc5cb-98a6-499f-9510-7156cff02aa4.png)

**Expected behavior**
Would love to actually use Fusion...

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360:
----> Online Build-Version: 2.0.12665
----> System Build-Version: 2.0.12670

- Graphics card model + Graphics card driver (Version number)
----> Intel Core i5-10500 @ 3.10GHz with sad integrated Graphics :(

- Operating system:
----> Kernel: 5.15.28, Manjaro XFCE

- DXVK- or OpenGL-Mode
----> tried both with a clean install, both didn't work

- Wineversion 7.4 (got installed the first time via the staging branch)

**the terminal output after launching Fusion360**
---> look at that my gist, because it's quite a chunky output
https://gist.github.com/thomas-repo/84fd7392bdf1744e7fd801f33463cb19

**Comment by cryinkfly** [comment]
@thomas-repo Thank you for your information! :+1: 

I found this line here:

> MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

... and that's just a bug under Intel! :-1: 

But there are several workarounds for this problem. ☝️

- https://forum.manjaro.org/t/cant-change-dev-i915-perf-stream-paranoid-to-0/66339/4
- https://www.reddit.com/r/wine_gaming/comments/m7ircp/mesaintel_warning_performance_support_disabled/
- https://forums.linuxmint.com/viewtopic.php?p=2124201

A solution would be:

![Bildschirmfoto_2022-04-07_13-04-31](https://user-images.githubusercontent.com/79079633/162185793-8b579338-a804-4a8d-a84f-c0bfdb2519d7.png)
_Link: https://forums.linuxmint.com/viewtopic.php?p=2124201_

I also recommend taking a look here, regardless of which Linux distribution is used:

- https://wiki.archlinux.org/title/intel_graphics

Because there some problems are addressed that can exist with Intel under Linux etc.! 😅

**Comment by platinum95** [comment]
I'm having the same issue on an Nvidia card, so Intel isn't the cause for me
