### ISSUE TITLE
Missing Fusion360 exe

### ISSUE THREAD

**Issue by guestisp** [cryinkfly/Autodesk-Fusion-360-for-Linux#215]
Fresh install on Ubuntu 21.04, no errors seen during the install, but as far as i can see, fusion were not installed.

`find $HOME -name Fusion360.exe`

return nothing

**Comment by alextrical** [comment]
Likewise i'm currently experiencing the same issue when installing on Fedora (tool-boxed) the closest i can see is 'FusionLauncher.exe' but that fails to launch, giving error `Configuration file 'C:\Program Files\Autodesk\webdeploy\production\6a0c9611291d45bb9226980209917c3d\FusionLauncher.exe.ini` is missing or incomplete
Please re-install the application, and contact support if this does not resolve the problem.

**Comment by JacobWarners** [comment]
Same issue, I was able to get it to load and then break by altering the script and targeting my .wine instead as it seemed to have more permissions.

**Comment by cryinkfly** [comment]
@JacobWarners 

> my .wine instead as it seemed to have more permissions.

Could you describe it in more detail?

---

Please look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/218#issuecomment-1108319516

**Comment by Noxdor** [comment]
I was yesterday night participating in #216 when I realized my real problem was this issue here. I just wanted to give a quick update, because I somehow made it work. I think it was the following steps, please someone follow and confirm:

1. Remove the current installation (delete `~/.wineprefixes/fusion360` and `~/.config/fusion360`)
2. Use the installer script from the README of this project for a fresh install.
3. After this, I could not find a Fusion360.exe in the wineprefix. What I did find was the Installer inside the wineprefix inside the users download folder. So I tried to run it manually again. A blank window opened and not much happened, I kept it open for a few minutes hoping it would install and killed the process after.
4. Going back to the `~/.config/fusion360/bin` folder I looked into the `launcher.sh` and tried the find command in line 48 and who would have known, the `Fusion360.exe` is found in `~/.wineprefixes/fusion360/drive_c/Program Files/Autodesk/webdeploy/production/22651d53e422c0183a6147899471ab1dca9a3f80/Fusion360.exe`!
5. So I just try to run the `launcher.sh` Script and voila! Fusion 360 opens without any issues and runs perfectly!

I think Step 3 did the trick but I am not entirely sure. I hope someone can confirm it or get it running with this.

I am running Garuda Linux (an Arch Distro) as a reference.

**Comment by joelawm** [comment]
> So I tried to run it manually again.
Which part did you try running again? the install.sh in .config/bin?

**Comment by joelawm** [comment]
> in my case it is located in ~/.wine/drive_c/users/giuseppe/AppData/Local/Autodesk/webdeploy/production/35db4e17dc0866380bef719f73dc6d050d7760ce/

I only have Microsfot in there for the ubuntu 21.10 install

**Comment by joelawm** [comment]
I get nothing back which is the weird part

**Comment by Kseii** [comment]
> I get nothing back which is the weird part

Same here. I do, however, have `FusionLauncher.exe`. Not sure if that's relevant though.

**Comment by alextrical** [comment]
I was getting the same here too. Not sure how much is related to this issue, and working in a Toolbox on Fedora Silverblue (due to it being atomic)

**Comment by alextrical** [comment]
As a sanity check to confirm i'm not missing something silly, these are the steps i followed:

#Hosts 
`127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4`
`::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 ip6-localhost ip6-loopback`
`127.0.1.1     Asus-Fedora`
`#::1 ip6-localhost ip6-loopback`
`fe00::0 ip6-localnet`
`ff00::0 ip6-mcastprefix`
`ff02::1 ip6-allnodes`
`ff02::2 ip6-allrouters`
`ff02::3 ip6-allhosts`

#Hostname 
`Asus-Fedora`

sudo dnf update && sudo dnf install zenity

mkdir -p "$HOME/.config/fusion-360/bin" && cd "$HOME/.config/fusion-360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x install.sh && bash install.sh && exit

**Comment by alextrical** [comment]
Just spotted an oddity while the script was installing.
`cd ~/.wineprefixes/fusion360/drive_c/Program\ Files/Autodesk/webdeploy/production/22651d53e422c0183a6147899471ab1dca9a3f80/`
I did a `ls` wile the first Fusion360 install pass was running and saw 'Fusion360.exe' as there, however it dissapeared once the second pass was run.

**Comment by Noxdor** [comment]
> Edit: Running the following as mentioned by @Noxdor made "fusion360.exe" come back `WINEPREFIX=~/.wineprefixes/fusion360 wine ~/.wineprefixes/fusion360/drive_c/users/$USER/Downloads/Fusion360installer.exe`

Yes this is exactly what I run, sorry for forgetting to include the command in my last comment. This brings back the "Fusion360.exe" and by that fixes (at least for me) the "launcher.sh" without changed it's target to `~/.wine` (the default wine prefix). Running it you should be able to run Fusion360 from the extra created fusion360 wineprefix in `~/.wineprefixes/fusion360`.

**Comment by mcbb2001** [comment]
> > Edit: Running the following as mentioned by @Noxdor made "fusion360.exe" come back `WINEPREFIX=~/.wineprefixes/fusion360 wine ~/.wineprefixes/fusion360/drive_c/users/$USER/Downloads/Fusion360installer.exe`
> 
> Yes this is exactly what I run, sorry for forgetting to include the command in my last comment. This brings back the "Fusion360.exe" and by that fixes (at least for me) the "launcher.sh" without changed it's target to `~/.wine` (the default wine prefix). Running it you should be able to run Fusion360 from the extra created fusion360 wineprefix in `~/.wineprefixes/fusion360`.

Followed the trail to here from issue 216, however after a fresh run of the install script it did successfully update.

upon launch of the desktop file I am immediately prompted with this window:
![image](https://user-images.githubusercontent.com/39408784/165866825-ebed3d93-fa06-4220-8385-82e5844ced05.png)
I then ran the command to find fusion360.exe and it returned nothing, so I followed your instructions above, and it launches to a window that hangs for a few minutes. After a few minutes of letting it hang I forced it closed (maybe I should have waited but oh well) and then attempted to launch fusion360 again, to the same issue. I can get the konsole logs if needed.

**Comment by spennydl** [comment]
@Noxdor 
>     3. After this, I could not find a Fusion360.exe in the wineprefix. What I did find was the Installer inside the wineprefix inside the users download folder. So I tried to run it manually again. A blank window opened and not much happened, I kept it open for a few minutes hoping it would install and killed the process after.
This worked for me! I did get another error and had to also install dotnet45, but I have a feeling that's either due to a bug in wine-mono or I have the wrong versions installed. Thanks for posting this!

@cryinkfly I'm curious as to why during the installation process the Fusion360Installer.exe is run twice?

**Comment by alextrical** [comment]
From what i can see the first install pass fails at some point and doesn't install all the required files, the second pass adds the final required files, though upon completion of the installer on the second pass, it looks like it still removes some files (notably the Fusion360.exe file). 

Running it as the 'GUI' version by omitting ` --quiet` seems to stop the installer prior to the point where it deletes the exe.

**Comment by alextrical** [comment]
Replacing line 219 with `WINEPREFIX=$wineprefixname wine $wineprefixname/drive_c/users/$USER/Downloads/Fusion360installer.exe -p deploy -g -f log.txt & ( sleep 60 ; killall streamer.exe ) & #Kill the window after being open for one minute`
Looks to be able to reliably create (and keep) the Fusion360.exe file

**Comment by cryinkfly** [comment]
@spennydl 

> @cryinkfly Ich bin neugierig, warum die Fusion360Installer.exe während des Installationsvorgangs zweimal ausgeführt wird?

It is run twice because not everything was always installed correctly the first time.

**Comment by maximevince** [comment]
> Just spotted an oddity while the script was installing. `cd ~/.wineprefixes/fusion360/drive_c/Program\ Files/Autodesk/webdeploy/production/22651d53e422c0183a6147899471ab1dca9a3f80/` I did a `ls` wile the first Fusion360 install pass was running and saw 'Fusion360.exe' as there, however it dissapeared once the second pass was run.
> 
> Edit: Running the following as mentioned by @Noxdor made "fusion360.exe" come back `WINEPREFIX=~/.wineprefixes/fusion360 wine ~/.wineprefixes/fusion360/drive_c/users/$USER/Downloads/Fusion360installer.exe`

This worked for me as well!

**Comment by Codesmith512** [comment]
I've been trying to get this setup inside a docker container with X11 forwarding, so I just ran into this whole fiasco myself, on top of some docker related stuff with gecko.

Basically, I have to run the install script, then manually run `Fusion360installer.exe` so that it prompts me to download gecko, even thought its installed system wide via pacman. After it installs gecko and launches to a blank screen, I let it sit there for 90 seconds, and forceably kill it.

After that, launching the app always prompts me to update, but it launches great whether or not I choose to update. I did have to modify the update script to kill the update process after 90 seconds though.

Wish I knew why the update process dies.

**Comment by cryinkfly** [comment]
Please look here: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/232#issuecomment-1144487489

**Comment by Satnet** [comment]
I'm having this exact issue on Windows. It all started with that Fusion 360 wouldn't update. So I uninstalled it and tried to reinstall. That's when the issues came. "WinError 2 file cant be found" so I looked in the log. It's the exact same error as in this Git issue. So I reinstalled my entire PC and this issue still persists. To be honest, I've been at this for an entire day now. Exhausted and angry.

```
Traceback (most recent call last):
  File "R:\Streamer\src\adsk\dls\streamer\process\process.py", line 1133, in execute
  File "R:\Streamer\src\adsk\dls\streamer\process\process.py", line 1080, in execute_without_errorhandling
  File "R:\Streamer\src\adsk\dls\streamer\process\process.py", line 906, in _config_app
  File "R:\Streamer\src\adsk\dls\streamer\process\process.py", line 1535, in _do_installation
  File "R:\Streamer\src\adsk\dls\streamer\process\process.py", line 403, in _executetasks
  File "R:\Streamer\src\adsk\dls\streamer\windows\platform.py", line 329, in create_launch_items
  File "E:\Jenkins\3P\PYTHON\3.9.6\WIN64_1\lib\subprocess.py", line 368, in check_call
  File "E:\Jenkins\3P\PYTHON\3.9.6\WIN64_1\lib\subprocess.py", line 349, in call
  File "E:\Jenkins\3P\PYTHON\3.9.6\WIN64_1\lib\subprocess.py", line 951, in __init__
  File "E:\Jenkins\3P\PYTHON\3.9.6\WIN64_1\lib\subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] File not found
```

**Comment by andrewazores** [comment]
If you're on Windows then you probably didn't use this project, which is for Linux only... sounds like it's just a Fusion 360 bug, so you'd need to report it to Autodesk.
