### ISSUE TITLE
'Open from my computer' file dialog not showing Linux filesystem *solved*

### ISSUE THREAD

**Issue by molove** [cryinkfly/Autodesk-Fusion-360-for-Linux#218]
**Describe the bug**
Since the new installer, when trying to open files from or export files to my computer the file dialog no longer gives me the ability to navigate the Linux filesystem and is restricted to the Wine filesystem

**To Reproduce**
1. Go to 'File menu/Open'
2. Click on 'Open from my computer'

**Expected behavior**
The file dialog should show / and (Z:) under 'My Computer', but they are missing and there is no up button to be able to navigate away from the Wine filesystem

**Screenshots**

This is what my file dialog looks like

![image](https://user-images.githubusercontent.com/20013346/164974942-60a3637b-89ad-4bba-9ef6-a2a776f946ec.png)

This is a screen shot of the file dialog from Meshmixer running in Wine showing access to the Linux file system

![image](https://user-images.githubusercontent.com/20013346/164975142-44c513c0-3a28-4966-8863-50ccf2ee6062.png)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360 - 2.0.12670
- Graphics card model + Graphics card driver (Version number) Nvidia GTX1060 6GB
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...) Manjaro
- Desktop environment (XFCE 4.16, Gnome 40, ...) KDE Plasma 5.24.4
- DXVK- or OpenGL-Mode - OpenGL

**Additional context**
This is probably just a setting in Wine but as it works correctly in other Wine apps I'm not sure how to go about fixing it

**Comment by cryinkfly** [comment]
### @molove This isn't a bug, it's a built-in security feature that I've enabled since the [last update](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v6.9) that keeps the Wine environment and your personal data separate!

![Bildschirmfoto_2022-04-25_11-11-36](https://user-images.githubusercontent.com/79079633/165058346-b6b8c36d-b0b4-4c61-a6bf-e5625a18ef65.png)

#### For this reason, I recommend that you watch the [video](https://youtu.be/shtPsaPYXog?t=2432) where I also discussed this innovation. Anyway, now it means, you have to switch directly to your Wineprefix and only from there you can upload files to Autodesk Fusion 360, for example!

> wineprefixname="$HOME/.wineprefixes/fusion360/drive_c/users/$USER/Documents"

**Comment by imagidan-ets** [comment]
For those using Bottles, go to your bottle and in settings go to Manage Drives and add a drive that points to a folder in your linux distribution that you want Fusion360 to access

**Comment by ThirtyThreeB** [comment]
I need a work around for saving files.  I understand how I would be able to manually add a file by placing in the folder in the .wineprefixes, but if I need to go the other way how can I do that.
I am currently unable to save files or export them, which means I cannot use a slicer or print.
