### ISSUE TITLE
Fusion stopping at the splash screen

### ISSUE THREAD

**Issue by kyngs** [cryinkfly/Autodesk-Fusion-360-for-Linux#240]
**Describe the bug**
While installing I get the log spammed by 
```
wine: could not open working directory L"unix\home\kyngs\.fusion360\bin\", starting in the Windows directory.
wine: could not open working directory L"unix\home\kyngs\.fusion360\bin\", starting in the Windows directory.
```
After the install is complete and I try to launch f360, after the updater exits, I get the same error and an error saying it cannot find the Fusion360 executable. Most likely because it is trying to find it under .wine

**To Reproduce**
1. Try to install f360
2. Attempt to launch it

**Expected behavior**
F360 should install and launch.

**Screenshots**

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360 - Not applicable
- Graphics card model + Graphics card driver (Version number) - Not applicable
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...) - Arch Linux
- Desktop environment (XFCE 4.16, Gnome 40, ...) - KDE
- DXVK- or OpenGL-Mode - Tried both

**Additional context**

**Comment by Codesmith512** [comment]
Hmmm, I get these messages in my log as well though I can launch Fusion 360 to the splash screen (as per #239 it hangs after that). I wonder if it's related, I'm also on Arch + KDE (though I doubt KDE would make a difference here)

**Comment by kyngs** [comment]
I did the install on my main computer a few days ago (also Arch + KDE) and it went fine, gonna post the logs when I get to it.

**Comment by Diazblo** [comment]
In my case I get same messages in my log but I can launch Fusion 360 and use it except that the splash logo keeps flickering on mouse movements.

**Comment by kyngs** [comment]
> Hmmm, I get these messages in my log as well though I can launch Fusion 360 to the splash screen (as per #239 it hangs after that). I wonder if there's something else at play here, I'm also on Arch + KDE (though I doubt KDE would make a difference here)
> 
> @kyngs Can you post the full log for installation and run? (something like `launch.sh 2>&1 | tee install.log` for installation and similar for launching the app)

After trying the installation today again, I experience the exact same thing as you. The splash screen appears then after a while disappears and exits with code 5.

**Comment by daveth** [comment]
> > Hmmm, I get these messages in my log as well though I can launch Fusion 360 to the splash screen (as per #239 it hangs after that). I wonder if there's something else at play here, I'm also on Arch + KDE (though I doubt KDE would make a difference here)
> > @kyngs Can you post the full log for installation and run? (something like `launch.sh 2>&1 | tee install.log` for installation and similar for launching the app)
> 
> After trying the installation today again, I experience the exact same thing as you. The splash screen appears then after a while disappears and exits with code 5.

Can confirm same here on Arch (i3wm if that matters), last couple of lines in the logs are as follows:

``
...
0488:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
0488:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
0488:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
034c:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\daev\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\f7a82f74-f909-49ad-ae46-a61decf4fdfc_i2.json.user.saving", 0x00000001, 0000000000000000, 000000000011EA00): stub
034c:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\daev\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\f7a82f74-f909-49ad-ae46-a61decf4fdfc_i2.json.user", 0x00000001, 0000000000000000, 000000000011EA00): stub

5 daev@monad .fusion360 $
```

Could Wine Mono be related? I noticed .NET is now required since a recent release.

**Comment by kyngs** [comment]
That could be it, however, I thought that wine would ask you to install it?

**Comment by kyngs** [comment]
So, today I tried reinstalling fusion both on my main PC and my notebook. On my main PC, it went fine and everything works.
However, on my NTB I still observe the same issues.

NTB Lenovo IdeaPad 5 Pro: AMD Ryzen 7 5800H (integrated GPU)
Main PC:
CPU: AMD Ryzen 9 5900X
GPU: Gainward RTX 3080

**Comment by Codesmith512** [comment]
@kyngs it might be useful to get a log of both computers launching the app so we can see side-by-side one that works and one that doesn't :thinking:

**Comment by Codesmith512** [comment]
Tried things again from scratch today. Seems to work out of the box now.

@kyngs Wanna give it another go?

**Comment by kyngs** [comment]
Might try.

**Comment by Benzolio** [comment]
I'm not sure if this is the same issue, but Fusion360 is hanging on the splash for me. I walked away for about an hour and fusion had crashed while I was away.
![image](https://user-images.githubusercontent.com/29846429/186558790-3ef297b8-817e-47ce-8043-8519e5f88649.png)
[backtrace.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/9421016/backtrace.txt)
`cd ~/.fusion360/wineprefixes/default/drive_c & ~/.fusion360/wineprefixes/default/box-run.sh 2>&1 | tee box-run.log`
I started this up this time with `cd ~/.fusion360/wineprefixes/default/drive_c & ~/.fusion360/wineprefixes/default/box-run.sh 2>&1 | tee box-run.log` and this is the resulting log: 
[box-run.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/9421095/box-run.log)

I installed with the script. (I'd previously tried a Snap which didn't even get to the splash image so I removed it, then the Bottle installer, which silently failed. )

My System:
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.19.1-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3 CPU 530 @ 2.93GHz
Memory: 7.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE2

If I end the task in WINE task manager, the next time I try to launch Fusion 360, it opens the Fusion utilities with options to repair, repairing didn't make a difference. I have not yet been able to get far enough along to log in with my autodesk account. 

I did not install wine in the install script, choosing to use my existing WINE 7.15-1 (multilib) since I already have a few other programs running in a different WINEPREFIX that I didn't want to mangle.

I hadn't tried Bottles before, and I'm not sure if this is that same issue or a side effect of semi-blindly jumping in to Bottles, and then trying the install script without first attempting to reverse of clean up whatever had been installed using the Fusion 360 Installer from within Bottles. Just hoping maybe these logs might be useful for anyone else troubleshooting this or similar issues.

**Comment by Siraman25** [comment]
I have the exact same issue as @Benzolio, and it also hangs for me after a couple of hours. Sometimes I also get to the Fusion utilities.
My system:
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 5.10.157-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Memory: 6.7 GiB of RAM
Graphics Processor: AMD Radeon Vega 8 Graphics
Manufacturer: HUAWEI

This is my log after i ran `box-run.sh` from the terminal:
[run_log.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/10235614/run_log.txt)

**Comment by Kyr4l** [comment]
same issue here, still no fix ?

**Comment by kyngs** [comment]
For some reason, it started working for me.

**Comment by n3oney** [comment]
> > > Hmmm, I get these messages in my log as well though I can launch Fusion 360 to the splash screen (as per #239 it hangs after that). I wonder if there's something else at play here, I'm also on Arch + KDE (though I doubt KDE would make a difference here)
> > > @kyngs Can you post the full log for installation and run? (something like `launch.sh 2>&1 | tee install.log` for installation and similar for launching the app)
> > 
> > 
> > After trying the installation today again, I experience the exact same thing as you. The splash screen appears then after a while disappears and exits with code 5.
> 
> Can confirm same here on Arch (i3wm if that matters), last couple of lines in the logs are as follows:
> 
> ```
> ...
> 0488:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
> 0488:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.5" not implemented
> 0488:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
> 034c:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\daev\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\f7a82f74-f909-49ad-ae46-a61decf4fdfc_i2.json.user.saving", 0x00000001, 0000000000000000, 000000000011EA00): stub
> 034c:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\daev\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\f7a82f74-f909-49ad-ae46-a61decf4fdfc_i2.json.user", 0x00000001, 0000000000000000, 000000000011EA00): stub
> 
> 5 daev@monad .fusion360 $
> ```
> 
> Could Wine Mono be related? I noticed .NET is now required since a recent release.

I'm fairly sure the missing .NET stuff is caused with [this](https://github.com/Winetricks/winetricks/pull/2025). Try downgrading cabextract to v1.9

**Comment by kyngs** [comment]
Closing, since the issue apparently fixed itself.

**Comment by Kyr4l** [comment]
this is still an issue
