### ISSUE TITLE
Application could not be started, or no application associated with the specified file. *solved*

### ISSUE THREAD

**Issue by cstles** [cryinkfly/Autodesk-Fusion-360-for-Linux#243]
**Describe the bug**
Fusion360.exe *does not exist* in any installs, only FusionLauncher.exe does. 
I have ran the installer countless times but this issue never resolves.

**To Reproduce**
1. Install
2. The launcher doesn't work in the first place, so you must change "LAUNCHER_RUN_FUSION360" to "LAUNCHER="$(find $HOME/.fusion360/wineprefixes/default -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.fusion360/wineprefixes/default" wine "$LAUNCHER""
3. Run
4. Errors out

**Expected behavior**
Run Fusion360.exe

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: 2.0.13168
- AMD ATI FirePro W5100, AMDGPU-pro
- Arch Linux, Linux 5.18.2
- DXVK and OpenGL

**Comment by Diazblo** [comment]
It is likely happening because of installation getting killed before it is completed as the 3 minute time may not be enough for your PC. The installer needs start and stop due to #232

**Try this :**
This will basically make the installation script wait for 10 minute instead of 3 minute.
* Before executing the installation script, we need to edit it. So only run the starting part 
`mkdir -p "$HOME/.fusion360/bin" && cd "$HOME/.fusion360/bin" && wget -N https://raw.githubusercontent.com/cryinkfly/Autodesk-Fusion-360-for-Linux/main/files/builds/stable-branch/bin/install.sh && chmod +x install.sh` 
* Open the install script in gedit 
`gedit ./install.sh`
* Edit the line 380 to from `sleep 3m` to `sleep 10m`
```
  function SP_FUSION360_INSTALL_STOP_1 {
      sleep 10m
      kill -9 $(ps aux |grep -i '\.exe' |awk '{print $2}'|tr '\n' ' ')
  }
```
* Now execute installation script
