### ISSUE TITLE
Autodesk Application Streaming showing only black

### ISSUE THREAD

**Issue by inkka04** [cryinkfly/Autodesk-Fusion-360-for-Linux#248]
During installation everything seems to go fine till the streamer.exe starts up. No crashing, just a window filled with only black.

Ideas?

**Comment by kfatehi** [comment]
I have the same problem. @inkka04 did you try the OpenGL mode? I have not yet tried it and have only been seeing the black screen for a few minutes so far and hoping it gets replaced with something visible.

![image](https://user-images.githubusercontent.com/175305/175754514-a269a216-5076-400e-8963-73c159819009.png)

**Comment by robcrossland** [comment]
I'm having the same issue- end result seems to be an installation with an empty fusionlauncher.exe.ini file

**Comment by badsmoke** [comment]
the same


ubuntu 22.04
both opengl and dx

**Comment by nmittow** [comment]
Ditto, same issue.  Both using installer script and walking through manually, Fusion360Installer.exe unpacks, opens the Autodesk Application Streaming window, shows black and hangs (process monitor showing streamer.exe at ~10% cpu usage but no other signs of life).

Fedora 36 xorg & kde
i9 12900k
GeForce RTX 2070

Appreciate all the work your doing, willing to provide more data if useful.

**Comment by hcooper** [comment]
Same here. On both OpenGL & DXVK

Running wine-7.11 (Staging)

Little idea how to troubleshoot it further!

**Comment by hcooper** [comment]
Errrr..... I happened to leave the black window open for ~20 minutes and it seems to have kept working. It eventually got to the addons list. I now have Fusion 360 installed and running.

**Comment by badsmoke** [comment]
thanks, that worked for me too "just wait" :-D

have not looked at the clock

**Comment by nmittow** [comment]
Following up, I too, just waited, but then had to do a bit of cleanup manually.  My process to a working install:

1. Follow manual installation located in the [documentation](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#configuring-access-to-the-distribution-repository-rhel-and-sle-only)
2. After running Fusion360Installer.exe, blank window opens
3. Minimize streamer.exe window then restore, and Fusion splash is present.
4. Go get dinner (to be safe I waited about 90min)
5. Complete the DXVK install steps (I did not attempt OpenGL install here)
6. Inspired by issue #215 , check to see if Fusion360.exe exists: `find $HOME -name Fusion360.exe`
7. Located Fusion360.exe as `$HOME/.fusion360/wineprefixes/default/drive_c/Program\ Files/Autodesk/webdeploy/production/RANDOMSTRING/Fusion360.exe`
8. Edited `$HOME/.fusion360/bin/launcher.sh` to skip the update check (comment out last 3 lines) & add line `LAUNCHER_RUN_FUSION360`
9. add `#!/bin/bash` to the beginning of `/home/usb/.fusion360/wineprefixes/default/box-run.sh`
10. Manually created a .desktop file for my system
11. Shazam, I got fusion on linux.
12. Remind myself that when fusion starts complaining about being out of date I need to manually run update.sh.

Vielen dank Cryinkfly, CAD is the only reason I've kept a windows box around until now, I can now live windows free!

**Comment by cryinkfly** [comment]
This bug is solved! :+1: I forgot add a line in my script. 🙃

**Comment by zakutin** [comment]
> Following up, I too, just waited, but then had to do a bit of cleanup manually. My process to a working install:
> 
>     1. Follow manual installation located in the [documentation](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation#configuring-access-to-the-distribution-repository-rhel-and-sle-only)
> 
>     2. After running Fusion360Installer.exe, blank window opens
> 
>     3. Minimize streamer.exe window then restore, and Fusion splash is present.
> 
>     4. Go get dinner (to be safe I waited about 90min)
> 
>     5. Complete the DXVK install steps (I did not attempt OpenGL install here)
> 
>     6. Inspired by issue [Missing Fusion360 exe *solved* #215](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/215) , check to see if Fusion360.exe exists: `find $HOME -name Fusion360.exe`
> 
>     7. Located Fusion360.exe as `$HOME/.fusion360/wineprefixes/default/drive_c/Program\ Files/Autodesk/webdeploy/production/RANDOMSTRING/Fusion360.exe`
> 
>     8. Edited `$HOME/.fusion360/bin/launcher.sh` to skip the update check (comment out last 3 lines) & add line `LAUNCHER_RUN_FUSION360`
> 
>     9. add `#!/bin/bash` to the beginning of `/home/usb/.fusion360/wineprefixes/default/box-run.sh`
> 
>     10. Manually created a .desktop file for my system
> 
>     11. Shazam, I got fusion on linux.
> 
>     12. Remind myself that when fusion starts complaining about being out of date I need to manually run update.sh.
> 
> 
> Vielen dank Cryinkfly, CAD is the only reason I've kept a windows box around until now, I can now live windows free!

Hi @nmittow,
I have a couple of questions:
1. Which version of wine did you install it on?
2. Did your installation end up clear or did you kill it after ~90 minutes?
3. Can you run simulations locally or it is failing?

**Comment by nmittow** [comment]
Howdy @zakutin ,

1) 7.12

2) Referencing steps 3 & 4 in my procedure, I had to kill it eventually.  The webinstaller seems to be downloading the install exe in the background just fine, but there is no sign of life in the install splashscreen/window.  I killed it after 90min ish, then dug around with find to figure out where it dumped that exe.

Additionally I doubt it actually takes 90min, it was just a convenient time for me to go get something to eat.  One could probably monitor their network io to figure out when the download has completed.

3) have not tried, might give something a go in the future weeks to see if it runs, however my use cases for fusion don't typically involve needing simulations.

It seems like Cryinkfly has updated his install script since these issues so I am curious as to whether many of these have been resolved.

**Comment by zakutin** [comment]
@nmittow,
thank you for your answer. Yeah, I pretty much did the same following the manual installation. The Fusion 360 is working itself, however, the simulation executed locally fails.

I'm sorry that I posting this off the topic, I was lurking around and ran into your relatively late installation experience. @cryinkfly is referencing to [this post](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v2.0) from May 2021, however, the installer has been modified by Autodesk since that time.

Could you please check if the simulation **executed locally** is working (e.g. simple beam with constraint and load)?
