### ISSUE TITLE
Updates fail

### ISSUE THREAD

**Issue by paukstelis** [cryinkfly/Autodesk-Fusion-360-for-Linux#297]
**Describe the bug**
An update is detected by the script but fails to apply an update.

**To Reproduce**
Launch fusion, connects to server, detects update, apply update, Fusion360.xxxx.update.exe downloads, then old version is launched.

**Expected behavior**
Update is applied.

**Screenshots**

**Desktop (please complete the following information):**
- Operating system (Ubuntu 22)
- Desktop environment ( Gnome )
-  OpenGL-Mode

**Additional context**
Only failure message is: `line 203: UP_FUSION360_INSTALL_UPDATE_PROGRESS_MAIN: command not found`

**Comment by kavourbm** [comment]
I believe I am experiencing the same issue, here is my terminal output as a txt file:

[fusionlaunch.txt](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/10677455/fusionlaunch.txt)

The error @paukstelis mentions appears on line 31 for me. The only way that I know this is happening at all is because when I try to open a file I edited on another computer, it tells me it cannot open it and fusion360 needs to be updated to the latest version

![image](https://user-images.githubusercontent.com/122492966/217308784-90294ed1-0588-4a57-a453-9727959378c6.png)


Relevant Info:
OS: Manjaro KDE
Using DX-9 mode in F360

**Comment by kavourbm** [comment]
So I tried to reinstall as a "fix", however, I ended up with the same internet issue that everyone else seemed to have for the past few weeks.

After the fix for that was found, it does appear to work correctly, however, it still seems to think there is a new update every time I launch despite it being up to date.

**Comment by Eric-Bwr** [comment]
Hm, for me the updates seem to install just fine. But the weird thing is, everytime I launch it, theres and supposed update. 
I can also open, install the update, which returns with good news that it has been installed, close, and reopen it again. It will say: Update available :) 

Ubuntu 22, Gnome, OGL Mode. Installed with default parameters. Added only the helical gear generator.

**Comment by Damien2s** [comment]
I experienced the same issue and managed to work around it by modifying  ~/.fusion360/bin/updater.sh
on line 203 replace

UP_FUSION360_INSTALL_UPDATE_PROGRESS_MAIN

by

UP_FUSION360_INSTALL_PROGRESS_MAIN

it successfully updated despite an error message at some point in the install process. And now it opens my projects which were developed with the latest version

**Comment by Derkun** [comment]
What solved this issue for me was to download the script again, but instead of running it off the bat - on line 284, remove the webarchive url and keep the autodesk url.

There are also issues with updating, where wine fails to use the c drive path for downloading a new version. That's why it always fails to update as it reverts to the preexisting "old" version in the c_drive downloads dir...

If I remember to write my discoveries down, I'll update this issue with the error logs and lines where update and install scripts fail. If anybody is urgently looking for a workaround, refer to the first paragraph.

**Comment by Derkun** [comment]
Probably related to #296 aswell

**Comment by atoav** [comment]
I went through the launcher scripts and the issue with my installation was that the `find "$WP_BOX" -name Fusion360.exe -printf "%T+ %p\n"` in the function `LAUNCHER_RUN_FUSION360` does not indeed find anything at all. The installer did not put any executable file in the WP_BOX directory.
