### ISSUE TITLE
Cannot export 3D model

### ISSUE THREAD

**Issue by dumbnerd08** [cryinkfly/Autodesk-Fusion-360-for-Linux#312]
When I design a model, click export, put in a name and format, press export, and wait for the export to finish, the file does not appear in my native file explorer or `ls -a` but it does appear in wine's file explorer. I am on Fedora Linux 37 and wine 8.0

**Comment by cryinkfly** [comment]
This behavior is not a bug, it is a security mechanism that I have enabled and configured that causes Fusion 360 to run in a kind of sandbox mode.

In order to be able to import or export data, you have to switch to the container (Wineprefix)!

This would be the path for a standard installation:

    $HOME/.fusion360/wineprefixes/default/drive_c/user/$USER/...

And then you will also see the various folders there, such as "Downloads, Documents, ...

... ... with which you can work.
