### ISSUE TITLE
Debian 12, Bookworm, support *Solved*

### ISSUE THREAD

**Issue by nmschulte** [cryinkfly/Autodesk-Fusion-360-for-Linux#336]
It seems trivial to add Debian 12 Bookworm support; would such a pull request be welcome?  Does Debian 11 support work on 12?  What about Debian Sid?

Semi-related, the installer assumes sudo is available, but this is not documented.  Is it possible to account for this somehow, but e.g. allowing user to manually execute super user commands (e.g. via copy/paste)?

Last, is it possible to use system-installed winetricks, or is it necessary to use the provided/installed winetricks?

Thank you for the effort; I have mused about using it, but spent the time bashing against FreeCAD's limitations and capabilities to accomplish my goals, in lieu of putting trust in this script or dipping into Autodesk's proprietary realm.

**Comment by cryinkfly** [comment]
@nmschulte Adding Bookworm support to Debian 12 seems trivial. Would such a pull request be welcome?

> Any kind of help is always welcome!

Does Debian 11 support work on 12? What about Debian Sid?

> I am currently working on an automatic detection of the different distro versions. See development branch: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/blob/dev/files/builds/stable-branch/bin/install.sh

The installer sometimes assumes that sudo is available, but this is not documented. Is there any way to explain this, but e.g. allow the user to execute superuser commands manually (e.g. by copy/paste)?

> Unfortunately, there are still a few errors in the code from the old days, which are still to be eliminated.

> Otherwise have a look at the documentation: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/wiki/Documentation

Finally, is it possible to use system-installed winetricks, or is it necessary to use the provided/installed winetricks?

> Yes it would be possible, but this Winetricks version is not always up to date! (downloads links, etc.)

Thank you for the effort; I considered using it, but spent the time denouncing FreeCAD's limitations and possibilities to achieve my goals, rather than trusting this script or delving into Autodesk's proprietary realm.

> Thank you for your feedback!

**Comment by cryinkfly** [comment]
Solved this issue: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/releases/tag/v7.6.9

**Comment by nmschulte** [comment]
Amazing, thank you!
