### ISSUE TITLE
AdskIdentityManager.exe has encountered a serious problem and needs to close

### ISSUE THREAD

**Issue by CawHaven** [cryinkfly/Autodesk-Fusion-360-for-Linux#441]
**Describe the bug**
After installing via the script, it tries to sign in but in encounters an error: "The program AdsIdentityManager.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience." Fusion 360 itself seems fine but whenever i click the sign in button, it brings this up and doesn't redirect. The same error happens on my proxmox VM as well.

**To Reproduce**
1. Start the script
2. Wait till it gets to the sign in page

**Expected behavior**
Redirects to the web ui sign in page

**Screenshots**
![2024-07-27_03-57](https://github.com/user-attachments/assets/a13d0ada-4a29-4099-9111-93e994447e01)

**Desktop (please complete the following information):**
- Version number of Autodesk Fusion 360: Latest
- Graphics card model + Graphics card driver (Version number): GA107M [GeForce RTX 3050 Ti Mobile]
- Operating system (OpenSUSE Leap 15.3, Fedora 34, ...): PopOS 22.04LTS
- Desktop environment (XFCE 4.16, Gnome 40, ...): KDE Plasma
- DXVK-: unknown what it selected when running the script

**Additional context**
Im using the script on a fresh install of PopOS on my Asus Flow Z13

**Comment by hamid-elaosta** [comment]
Just tried to install on Ubuntu 22.04, Gnome 42.9, GTX 1080 Ti, Nvidia 555, selected DXVK, only browser is Firefox.

Same issue you're having.

**Comment by wegel** [comment]
Same here running on Arch Linux and an AMD GPU, tried both DXVK and OpenGL.

**Comment by tomcass240** [comment]
same problem here

**Comment by cryinkfly** [comment]
I have the same issue!

**Comment by vrme007** [comment]
Same

**Comment by Lumbeseckel** [comment]
Same here. OpenSUSE Tumbleweed 20240725

**Comment by Lumbeseckel** [comment]
I think this is partly the same error as [this](https://github.com/Thermionix/fusion360/issues/39) and especially this: #432

**Comment by CawHaven** [comment]
> I think this is partly the same error as [this](https://github.com/Thermionix/fusion360/issues/39) and especially this: #432
> 
> EDIT: Seems this is a bug in Wine. See [BugReport](https://bugs.winehq.org/show_bug.cgi?id=56915). Maybe we can switch back to an older version of fusion for testing (before july)?

How would I access the older version of fusion360?

**Comment by PudlatyPL** [comment]
same

**Comment by cryinkfly** [comment]
Otherwise, it is a general problem:

https://www.autodesk.de/support/technical/article/caas/sfdcarticles/sfdcarticles/DEU/Fusion-360-does-not-launch-Error-displayed-The-code-execution-can-not-proceed-because-of-dll.html

You can start the tool, but the repair is also unsuccessful.

See instructions: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Overview-of-Fusion-360-Safe-Mode.html

![Bildschirmfoto vom 2024-07-29 12-05-12](https://github.com/user-attachments/assets/e5336c5d-fbf9-493e-8d6a-16d744025dde)

![Bildschirmfoto vom 2024-07-29 12-10-56](https://github.com/user-attachments/assets/ebc821ac-bc25-4574-9a3c-fbd7b19cecfa)

I also installed the Autodesk Identity Manager manually and changed the path in the .desktop file. But that didn't work either!

Here is the link: https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/7zbgTemIhA3ltRs4eACL0g.html

![Bildschirmfoto vom 2024-07-29 11-39-48](https://github.com/user-attachments/assets/c68dfaf1-242c-4c48-8958-d8fa7ce2d8f1)
![Bildschirmfoto vom 2024-07-29 11-41-08](https://github.com/user-attachments/assets/8bf562d9-e19e-473b-aae1-e00be61493c8)

**Comment by cryinkfly** [comment]
I have solved this bug and it works with the newest wine version: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/432#issuecomment-2255603453
